### ISSUE TITLE
多平台支持

### ISSUE THREAD

**Issue by g-plane** [IceLitty/Minecraft-Command-Helper#1]
.net 目前只支持 Windows 而已，为什么不考虑弄个跨平台呢？(.net core不算)

**Comment by IceLitty** [comment]
外观还是基于Mahapp了，不过自从发到mcbbs之后用这个第三方的人多了很多，想换Material的那个试试_(:з)∠)_
没怎么碰过qt，好像多平台Net的话只能用Mono吗…还不清楚Wine支不支持现在的MCH……
大概不太会去碰做多平台这个了，除非用cpp的话…大概是因为不会(懒)CPP吧qwq

**Comment by g-plane** [comment]
Qt 挺好的，不过它有个缺点是不能跨平台交叉编译。

**Comment by pca006132** [comment]
其实你可以考虑js...直接放在网上就好。毕竟这个逻辑不太难

**Comment by g-plane** [comment]
@pca006132 貌似这个软件最初是为了不依赖网络而开发的（不对请指出）。不过 Electron 也是挺好的。

**Comment by kj415j45** [comment]
.NET 在linux上有mono可用，主要是你大量使用了System.Windows.Input(windows平台类库)导致跨平台失败(其实只要不用针对windows平台的类库就不会有跨平台问题)

**Comment by IceLitty** [comment]
@g-plane 然而，其实做成网页版有个好处就是既能在线又能离线还能多客户端例如手机，仔细一想当初是因为自学C#才决定用C#来写的…一开始winform的代码都还在电脑里，从改成wpf开始才推github……

**Comment by g-plane** [comment]
现在有不少桌面程序是用 Electron 开发的，例如 VS Code
