### ISSUE TITLE
你还更新吗？

### ISSUE THREAD

**Issue by myunco** [IceLitty/Minecraft-Command-Helper#2]
这么久没更新 是有事还是不想更新了？

**Comment by IceLitty** [comment]
看情况，目前1.12除了新物品没什么功能化的吧（function也是和loottable一样文件形式的不过那个只是执行指令呀？并不是那么难用的功能，新物品的id的话之后有时间弄吧

**Comment by IceLitty** [comment]
2.8.7.1已更新mc1.12 :)

**Comment by myunco** [comment]
不知道复制还会不会崩溃

**Comment by IceLitty** [comment]
会的2333，主要是我这里没触发过崩溃，还不知道原因，pa那里给了我几个其他的Clipboard使用方法，刚好碰到一个好友也有崩溃的问题，于是找她试了下但是还是不行……于是只能用检索来手动复制了……

**Comment by myunco** [comment]
我也不知道什么原因，我在其他电脑上复制不会崩溃 在我电脑上就崩溃。 都是.net 4.6.2 系统都是Win7 64

**Comment by IceLitty** [comment]
看了下虚拟机，win7x64 net4.5，复制没问题
net版本不至于呀，我记得在4.6出来之前就有人回复过说会有问题，而且目录下带的config是指定4.5的

好吧不是指定4.5…看了下msdn上说只是支持4.5及以上
