### ISSUE TITLE
加油【我觉得这不应该开 issue】

### ISSUE THREAD

**Issue by ghost** [IceLitty/Minecraft-Command-Helper#3]
论坛环境越来越差有目共睹；垃圾百度云逼死多少开发者？只能说希望作者不要灰心把，加油。（词穷）
另外，我可以帮忙做一份相对快(服务器在台湾/香港两节点)的 mirror，毕竟 GitHub 用的是 Amazon S3，国内下载速度太XXXX.

**Comment by IceLitty** [comment]
感谢，将最后版本做外链即可，因为要等mc1.13更新后会去重新制作这个项目，届时也会去找适合的新网盘：)
